export const getNames = () => {
  return {
    A: [
      "lamarcusaldridge",
      "rayallen",
      "giannisantetokounmpo",
      "carmeloanthony",
    ],
    B: ["kobebryant", "charlesbarkley", "larrybird", "bradleybeal"],
    C: ["stephencurry", "vincecarter", "tysonchandler", "dellcurry"],
    D: ["timduncan", "kevindurant", "clydedrexler", "anthonydavis"],
    E: ["patrickewing", "anthonyedwards", "joelembiid"],
    F: ["de'aaronfox", "derrickfavors", "markellefultz"],
    G: ["kevingarnett", "paugasol", "manuginóbili", "dariusgarland"],
    H: ["jamesharden", "dwighthoward", "tobiasharris"],
    I: ["andreiguodala", "alleniverson", "sergeibaka", "kyrieirving"],
    J: ["michaeljordan", "lebronjames", "magicjohnson", "deandrejordan"],
    K: ["jasonkidd", "shawnkemp", "andreikirilenko", "kylekorver"],
    L: ["kylelowry", "damianlillard", "kawhileonard", "zachlavine"],
    M: ["karlmalone", "mosesmalone", "reggiemiller", "shawnmarion"],
    N: ["dirknowitzki", "stevenash", "joakimnoah"],
    O: ["hakeemolajuwon", "victoroladipo", "lamarodom"],
    P: ["chrispaul", "scottiepippen", "garypayton", "paulpierce"],
    Q: ["trevelinqueen", "chrisquinn", "timquarterman"],
    R: ["juliusrandle", "davidrobinson", "dennisrodman", "andreroberson"],
    S: ["domantassabonis", "johnstockton", "dennisschröder"],
    T: ["isiahthomas", "isaiahthomas", "jasonterry", "jaysontatum"],
    U: ["ekpeudoh", "imeudoka"],
    V: ["jonasvalančiūnas", "nikolavučević", "fredvanvleet"],
    W: ["dwyanewade", "russellwestbrook", "kembawalker"],
    Y: ["traeyoung", "thaddeusyoung", "omeryurtseven"],
    Z: ["codyzeller", "ivicazubac"],
  };
};
