export const teams = {
  east: {
    ATL: "Atlanta Hawks",
    BOS: "Boston Celtics",
    BRK: "Brooklyn Nets",
    CHO: "Charlotte Hornets",
    CHI: "Chicago Bulls",
    CLE: "Cleveland Cavaliers",
    DET: "Detroit Pistons",
    IND: "Indiana Pacers",
    MIA: "Miami Heat",
    MIL: "Milwaukee Bucks",
    NYK: "New York Knicks",
    ORL: "Orlando Magic",
    TOR: "Toronto Raptors",
    PHI: "Philadelphia 76ers",
    WAS: "Washington Wizards",
  },
  west: {
    DAL: "Dallas Mavericks",
    DEN: "Denver Nuggets",
    GSW: "Golden State Warriors",
    HOU: "Houston Rockets",
    LAC: "Los Angeles Clippers",
    LAL: "Los Angeles Lakers",
    MEM: "Memphis Grizzlies",
    MIN: "Minnesota Timberwolves",
    NOP: "New Orleans Pelicans",
    OKC: "Oklahoma City Thunder",
    PHO: "Phoenix Suns",
    POR: "Portland Trail Blazers",
    SAC: "Sacramento Kings",
    SAS: "San Antonio Spurs",
    UTA: "Utah Jazz",
  },
};
